spring:
  application:
    name: his-api
  servlet:
    # 文件上传功能
    multipart:
      enabled: true # 开启文件上传功能
      max-file-size: 20MB # 单个文件的最大体积【不能超过20MB】
      max-request-size: 20MB # HTTP整个请求体积最大【不能超过20MB】
  # druid数据库（mysql）连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据库连接池的实现类
    # url 属性必须放在这里，否则启动失败
    url: jdbc:mysql://localhost:8066/his?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai # 数据库连接地址
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
      username: root
      password: abc123456
      initial-size: 8 # 初始的连接池数量（建议：CPU内核的1-2倍）
      max-active: 16 # 最大连接数（建议：初始连接数的1倍）
      min-idle: 8 # 最小冗余连接数（建议：与初始连接数保持一致）
      max-wait: 60000 # 最大等待连接的空闲时间
      test-while-idle: true # 让数据库连接池时不时去监测空闲连接对象是否有效，若无效则销毁
      test-on-borrow: true # 监测连接是否有效
      test-on-return: false # 监测归还的连接对象是否有效（使用时监测就行，归还时可不进行监测）
      validation-query: SELECT 1 # 用于监测是否有效的SQL语句，可以自己规定

# 服务器配置
server:
  jetty:
    threads: # 线程池配置
      acceptors: 4 # acceptors线程池，用于接受http请求的线程数【内核个数的1到2倍】
      selectors: 8 # selectors线程池处理HTTP数据包的线程数【设置为 acceptors 的2两倍】
      # worker 线程池负责调用web方法
      min: 8 # 最少线程数
      max: 200 # 最大线程数
  port: 7700 # jetty启动的端口号
  servlet:
    context-path: /his-api # web服务的相对路径